### PR TITLE
Options Menu

### PR DESCRIPTION
**Pull request by d5c4b3**
I find myself resizing the window every time I pop it out. I added a small options_ui page that will let you set the width and height you want the popped out window to be. This could probably be improved a bit. 

I have never used half the technologies here, so if I have done something incorrect it's probably out of ignorance. If there is a better way to do anything I did here I will do my best to go back and change it.

### CODE REVIEW

**Comment by rthaut** [comment]
@d5c4b3 this is fantastic. Sorry I didn't take a look at it sooner. I have had multiple requests (via email and reviews) for similar functionality, and I just now got around to writing up a ticket.

I don't think I am going to merge this as-is, for a couple of reasons.
1) If you look at #21, I'm hoping to retain the ability for users to have the popout window open at the same size as the current video player (which was the reasoning behind using `player.getWidth() || this.defaults.width`). Obviously if the user wants to set a specific size, we would use the values they provided.
2) I'm also not 100% certain using sync storage is the best approach, as a "desired" resolution for one computer may not be appropriate for other computers the user has the extension installed on. Perhaps using a percentages, rather than pixels, would prevent this from being a problem, but I think ideally the user could choose pixels or percentages.

That said, this is a fantastic start for the options page, so I am going to use as much of this as I can as the foundation. I will get a demo options page setup on CodePen and add the link here; I would love to get your feedback and/or see if you want to code something to match, once the functionality is finalized.

**Comment by rthaut** [comment]
@d5c4b3 (again) [Here's a mockup for the Options page](https://codepen.io/rthaut/full/xmWydM) that covers most of the concerns I had, as well as meeting both of the current requests that deal with configurable settings (#20 and #21).

Obviously the mockup doesn't cover any of the adjustments that would need to be made to actually integrate these options, but I'm open to feedback suggestions on the UI itself for now.

**Comment by d5c4b3** [comment]
I completely understand not wanting to merge as is. Not using sync storage makes sense. It didn't really cross my mind that you would want different settings on different devices, but it makes perfect sense.

I think the mockup looks good. It currently shows the percent sign regardless of what you have selected though. I would love to work on this in my free time.

**Comment by rthaut** [comment]
@d5c4b3 I am going to close this Pull Request, but please know that I am very grateful to you for taking the time to work on the original implementation. It gave me the motivation to document and begin work on the various requests/complaints I've had since releasing the Extension, most of which were at the bottom of my list of priorities, as they needed a way to be configurable by the user.

I don't want your contribution to go unrecognized outside of this PR thread, either, so I will be adding you as a contributor on the main README document.

Finally, if you would like to take a look at the upcoming version 3.0, I have setup a [project board](https://github.com/rthaut/YouTubePopoutPlayer/projects/2), and the [feature/options-popout-size branch](https://github.com/rthaut/YouTubePopoutPlayer/tree/feature/options-popout-size) has my work on the new/improved features so far.

**Pull request closed without merging**
